#' Observe a spectrum with 4FS ETC
#'
#' @description Take an input spectrum and mock observe using the 4MOST ETC. You must have
#' the 4MOST ETC software installed and executable from the command line using command '4FS_ETC'. If you
#' do not have this, contact L. Davies <luke.j.davies@uwa.edu> for further instructions.
#' Take in output of makeSpec() and a given set of paramters such a sexposure time, number of subexposures
#' and instrumental/observing set up from 4MOST. Returns a list with various observational paramters and 
#' can also save the ETC outputs and FITS files directly.
#' 
#' @param spec input list contianing spectral information. Minimum requirements are
#' wave=vector of wavelengths in angstrom and flux=vector of fluxes in erg/s/cm2/Angstrom.
#' This is ideally the output of makeSpec(), which contains all of the relavent paramters.         
#' @param expMin Total exposure time to simulate observation  
#' @param nSub number of sub-exposure in expMin
#' @param SKYBRIGHT_TYPE where to measuresky brightness ZENITH or LOCAL?
#' @param AIRMASS simulated airmass of observation
#' @param IQ image quality value to simulate (V-band,FWHM,arcsec) 
#' @param SKYBRIGHT sky brightness in mag/arcsec^2
#' @param TILT fibre tilt in mm
#' @param MISALIGNMENT fibre misallignment in arcsec
#' @param systemModDir IMPORTANT: directory location of 4FS system files. Will be something like '4FS-ETC_app/4FS_ETC_system_model_v0.2/' 
#' @param keepFITS keep FITS files, etc generated by 4FS ETC?
#' @return List containing lost fo things!
#' @author L. Davies <luke.j.davies@uwa.edu>
#' @examples 
#' spec<-makeSpec(id='D134', z=zTest, mag=19.8, band='VST_r', col=0.55, mass=10.2,sfr=7,agn='F')
#' observeSpec4FSOut<-observeSpec4FS(spec, expMin=60, nSub=3, keepFITS=F)
#' magplot(observeSpec4FSOut$blueRawWave, observeSpec4FSOut$blueRawFlux, type='l', col='blue', xlim=c(3500,10000), ylim=c(0, max(c(observeSpec4FSOut$blueRawFlux,observeSpec4FSOut$greenRawFlux,observeSpec4FSOut$redRawFlux),na.rm=T)), xlab='Wavelength, Ang', ylab='Counts')
#' lines(observeSpec4FSOut$greenRawWave, observeSpec4FSOut$greenRawFlux, type='l', col='darkgreen')
#' lines(observeSpec4FSOut$redRawWave, observeSpec4FSOut$redRawFlux, type='l', col='red')
#' @export
observeSpec4FS<-function(spec, expMin=120, nSub=4, SKYBRIGHT_TYPE='ZENITH', AIRMASS=1.4, IQ=1.1, SKYBRIGHT=21.77, TILT=6.0, MISALIGNMENT=0.1, systemModDir='/Applications/4FS-ETC_app/4FS_ETC_system_model_v0.2/', keepFITS=TRUE){
    
    if(is.null(spec$id)==T | is.na(spec$mag)==T){spec$id<-'tmp'}
    if(is.null(spec$z)==T | is.na(spec$z)==T){spec$z<-0}
    if(is.null(spec$mag)==T | is.na(spec$mag)==T){spec$mag<-20}
    
    system(paste('rm -rf ', spec$id,'_ETCout',sep=''))
    system(paste('mkdir ', spec$id,'_ETCout',sep=''))
    dir<-paste(spec$id,'_ETCout/',sep='')  
    
    fname<-paste(spec$id,'.fits',sep='')
    
    load(paste(.libPaths(),'/FourXP/data/BaseAxDat.Rdata',sep=''))
    axDat$crval[1]<-min(spec$wave)
    axDat$cdelt[1]<-spec$wave[2]-spec$wave[1]
    axDat$ctype[1]<-'LINEAR'
    axDat$cunit[1]<-'Angstrom'
    axDat$len[1]<-length(spec$flux)
    axDat$len[2]<-1
    writeFITSim(cbind(spec$flux), file = paste(dir,fname, sep=''), axDat = axDat, type='single')
    write.fitskey('OBJECT',spec$id, paste(dir,fname, sep=''), comment = 'redshift', hdu = 1)            
    write.fitskey('Z',spec$z, paste(dir,fname, sep=''), comment = 'redshift', hdu = 1)
    write.fitskey('BAND',spec$band, paste(dir,fname, sep=''), comment = 'band', hdu = 1)
    write.fitskey('MAG',spec$mag, paste(dir,fname, sep=''), comment = 'magnitude in band', hdu = 1)
    write.fitskey('CRTYPE1','WAVE', paste(dir,fname, sep=''), comment = 'X-axis type', hdu = 1)
    write.fitskey('BUNIT','erg/s/cm2/Angstrom', paste(dir,fname, sep=''), comment = 'flux density unit', hdu = 1)
    write.fitskey('ABMAG AB',spec$mag, paste(dir,fname, sep=''), comment = 'SDSS r-mag', hdu = 1)
    write.fitskey('RESOLUTN',2, paste(dir,fname, sep=''), comment = 'resolution', hdu = 1)
    


    fileConn<-file(paste(dir,'tmp.ETC',sep=''))
    writeLines("#OBJECTNAME    FILENAME    RULESET   SIZ   REDSHIFT     MAG    MAG_RANGE", fileConn)   
    close(fileConn)
    
    cat(paste(spec$id,'    ',dir,spec$id,'.fits', '   NONE   0    0   ',spec$mag, '   ',spec$mag, sep='') ,'\n',file=paste(dir,'tmp.ETC',sep=''),append=TRUE)
    
    
    #system(paste('cp ',.libPaths(),'/FourXP/data/ETC_input_params_middle.txt ',dir,'ETC_input_params_tmp.txt', sep=''))
    
    fileConn<-file(paste(dir,'ETC_input_params_tmp.txt',sep=''))
    writeLines(paste("SIM.CODE_NAME                = '",spec$id,"'",sep=''), fileConn)
    close(fileConn)
    
    cat(paste("SIM.OUTDIR                   = '",dir,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.MODE                     = 'CALC_SNR'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.OUTPUT                   = 'SUMMARY,SPECTRA_FLUENCE,SPECTRA_NOISE, SPECTRA_SNR'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.SPECFORMAT               = 'TABLE,NATIVE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.CLOBBER                  = FALSE",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("TEMPLATES.FILENAME           = '",dir,"tmp.ETC'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("RULELIST.FILENAME            = 'NONE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("RULESETLIST.FILENAME         = 'NONE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NUM_FILTERS              = 5",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER.MAGSYS       = 'AB'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER1.NAME        = 'SDSS u'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER1.FILENAME    = '",systemModDir,"filter_curves/SDSS_u_transmission_curve.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER2.NAME        = 'SDSS g'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER2.FILENAME    = '",systemModDir,"filter_curves/SDSS_g_transmission_curve.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER3.NAME        = 'SDSS r'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER3.FILENAME    = '",systemModDir,"filter_curves/SDSS_r_transmission_curve.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER4.NAME        = 'SDSS i'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER4.FILENAME    = '",systemModDir,"filter_curves/SDSS_i_transmission_curve.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER5.NAME        = 'SDSS z'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SIM.NORM_FILTER5.FILENAME    = '",systemModDir,"filter_curves/SDSS_z_transmission_curve.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.FIBER_DIAM           = 1.45",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.EFFECTIVE_AREA       = 8.3975",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.SKYSUB_RESIDUAL      = 0.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.NUM_ARMS             = 3",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    
    cat(paste("SPECTRO.ARM1.CODENAME        = 'LRS_blue'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.RES_FILENAME    = '",systemModDir,"LRS/4MOST_LRS_resolution_curve_middle_interp_blue.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.TPUT_FILENAME   = '",systemModDir,"LRS/lrs_blue_material_4fs_efficiency_total.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.APER_SIZE       = 4.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.APER_EEF        = 0.9545",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.PEAK_PIX_FRAC   = 0.3702",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.READ_NOISE      = 2.5",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.DARK_CURRENT    = 3.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.FULL_WELL       = 350000",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.BINNING.DISP    = 1",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.BINNING.CROSS   = 1",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.LAMBDA.TYPE     = 'FULLFILE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM1.LAMBDA.FILENAME = '",systemModDir,"LRS/4MOST_LRS_wavelength_solution_middle_interp_blue.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    
    cat(paste("SPECTRO.ARM2.CODENAME        = 'LRS_green'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.RES_FILENAME    = '",systemModDir,"LRS/4MOST_LRS_resolution_curve_middle_interp_green.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.TPUT_FILENAME   = '",systemModDir,"LRS/lrs_green_material_4fs_efficiency_total.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.APER_SIZE       = 4.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.APER_EEF        = 0.9545",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.PEAK_PIX_FRAC   = 0.3702",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.READ_NOISE      = 2.5",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.DARK_CURRENT    = 3.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.FULL_WELL       = 350000",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.BINNING.DISP    = 1",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.BINNING.CROSS   = 1",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.LAMBDA.TYPE     = 'FULLFILE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM2.LAMBDA.FILENAME = '",systemModDir,"LRS/4MOST_LRS_wavelength_solution_middle_interp_green.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    
    cat(paste("SPECTRO.ARM3.CODENAME        = 'LRS_red'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.RES_FILENAME    = '",systemModDir,"LRS/4MOST_LRS_resolution_curve_middle_interp_red.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.TPUT_FILENAME   = '",systemModDir,"LRS/lrs_red_material_4fs_efficiency_total.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.APER_SIZE       = 4.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.APER_EEF        = 0.9545",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.PEAK_PIX_FRAC   = 0.3702",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.READ_NOISE      = 2.5",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.DARK_CURRENT    = 3.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.FULL_WELL       = 350000",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.BINNING.DISP    = 1",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.BINNING.CROSS   = 1",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.LAMBDA.TYPE     = 'FULLFILE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SPECTRO.ARM3.LAMBDA.FILENAME = '",systemModDir,"LRS/4MOST_LRS_wavelength_solution_middle_interp_red.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    
    cat(paste("FIBRECOUPLING.TYPE           = 'FILE'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("FIBRECOUPLING.FILENAME       = '/",systemModDir,"fibre_coupling/geometrical_throughput.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("FIBRECOUPLING.FRAC_SKY       = 1.0",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SKY.TRANSMISSION.FILENAME    = '",systemModDir,"sky/paranal_sky_transmission_vectors.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("SKY.EMISSION.FILENAME        = '",systemModDir,"sky/paranal_sky_emission_vectors.fits'", sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    
    cat(paste("OBS_PARAMS.INTERP_METHOD     = 'NEAREST'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.SKYBRIGHT_TYPE    = '",SKYBRIGHT_TYPE,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.AIRMASS           = '",AIRMASS,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.IQ                = '",IQ,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.SKYBRIGHT         = '",SKYBRIGHT,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.TILT              = '",TILT,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.MISALIGNMENT      = '",MISALIGNMENT,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.TEXP              = '",expMin*60.,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    cat(paste("OBS_PARAMS.NSUB              = '",nSub,"'",sep=''),'\n', file=paste(dir,'ETC_input_params_tmp.txt',sep=''),append=TRUE)
    
    ParaFile<-read.table(paste(dir,'ETC_input_params_tmp.txt',sep=''))
    
    blue_thru_file<-paste(systemModDir, "LRS/lrs_blue_material_4fs_efficiency_total.fits", sep='')
    green_thru_file<-paste(systemModDir, "LRS/lrs_green_material_4fs_efficiency_total.fits", sep='')
    red_thru_file<-paste(systemModDir, "LRS/lrs_red_material_4fs_efficiency_total.fits", sep='')
 
    system(paste('4FS_ETC PARAM_FILENAME=',dir,'ETC_input_params_tmp.txt \ >& ',dir,'etc.log &', sep=''))
    
    Sys.sleep(2)
    
    results_b<-readFITS(paste(dir,'specout_template_',spec$id,'_LRS_blue.fits',sep=''), hdu=2)
    results_g<-readFITS(paste(dir,'specout_template_',spec$id,'_LRS_green.fits',sep=''), hdu=2)
    results_r<-readFITS(paste(dir,'specout_template_',spec$id,'_LRS_red.fits',sep=''), hdu=2)

    # define band-specific fluxes
    red_fluxA<-(results_r$col[[3]])
    green_fluxA<-(results_g$col[[3]])
    blue_fluxA<-(results_b$col[[3]])
    
    # define band-specific wavelengths
    red_wave<-results_r$col[[1]]
    green_wave<-results_g$col[[1]]
    blue_wave<-results_b$col[[1]]
    
    # define band-specific nosie
    red_noise<-results_r$col[[4]]
    green_noise<-results_g$col[[4]]
    blue_noise<-results_b$col[[4]]
    
    # define band-specific S/N ratio
    red_SNR<-results_r$col[[5]]
    green_SNR<-results_g$col[[5]]
    blue_SNR<-results_b$col[[5]]
    
    blue_thru<-readFITS(blue_thru_file, hdu=1)
    blue_thruWave<-blue_thru$col[[1]]*10
    blue_thruTrans<-blue_thru$col[[12]]
    
    green_thru<-readFITS(green_thru_file, hdu=1)
    green_thruWave<-green_thru$col[[1]]*10
    green_thruTrans<-green_thru$col[[12]]
    
    red_thru<-readFITS(red_thru_file, hdu=1)
    red_thruWave<-red_thru$col[[1]]*10
    red_thruTrans<-red_thru$col[[12]]
    
    if (keepFITS==F){system(paste('rm -rf ', spec$id,'_ETCout',sep=''))}
  
    para<-list(id=spec$id, dir=dir, mag=spec$mag, expMin=expMin, nSub=nSub, z=spec$z, blueRawFlux=blue_fluxA, greenRawFlux=green_fluxA, redRawFlux=red_fluxA, blueRawWave=blue_wave, greenRawWave=green_wave, redRawWave=red_wave, blueRawNoise=blue_noise, greenRawNoise=green_noise, redRawNoise=red_noise, blueRawSNR=blue_SNR, greenRawSNR=green_SNR, redRawSNR=red_SNR, blue_thruWave=blue_thruWave, green_thruWave=green_thruWave, red_thruWave=red_thruWave, blue_thruTrans=blue_thruTrans, green_thruTrans=green_thruTrans, red_thruTrans=red_thruTrans, SKYBRIGHT_TYPE=SKYBRIGHT_TYPE, AIRMASS=AIRMASS, IQ=IQ, SKYBRIGHT=SKYBRIGHT, TILT=TILT, MISALIGNMENT=MISALIGNMENT, systemModDir=systemModDir, blue_file=paste(dir,'specout_template_',spec$id,'_LRS_blue.fits',sep=''),green_file=paste(dir,'specout_template_',spec$id,'_LRS_green.fits',sep=''),red_file=paste(dir,'specout_template_',spec$id,'_LRS_red.fits',sep=''), blue_thru_file=blue_thru_file, green_thru_file=green_thru_file, red_thru_file=red_thru_file, Param=ParaFile, ParaFile=paste(dir,'ETC_input_params_tmp.txt',sep=''))
    return(para)
}